flatironinstitute/CaImAn

ca_source_extraction/utilities.py
demo.py

We had some issues with ipcluster start and stop on our server. This patch makes the process a bit more robust.

Make ipcluster start and stop more robust

---

ca_source_extraction/spatial.py
ca_source_extraction/utilities.py

Hi Andrea,
great progress on the python implementation! Finally I could gladly switch away from matlab.
Using your code I stumbled upon and fixed few issues:
- nnls, sometimes called in lars_regression_noise, needs some vector as arg, hence the ravel in line 610 of spatial.py. Also, nnls returns a tuple, of which only the first element is expected. (consider using HALS instead of scipy's nnls, which is faster in my experience, if speed is an issue)
- In nb_view_patches the numbering of shapes and activities didn't match. Fixed in lines 864, 870 in utilities.py
- I added an argument to plot_contours (line 469, 525 in utilities.py) to set the color, cause the default blue can sometimes hardly be seen. 
My editor did some PEP8 auto-formatting and inserted/deleted some spaces, hence …

Smallfixes

---

ca_source_extraction/utilities.py

A minor modification, so that memmap from other folders can be loaded properly.

allow loading memmap in non-source folder

---

.travis.yml
Dockerfile
ca_source_extraction/tests/test_demo.py

Hey @agiovann, 
this PR fixes some installation problems:
* it moves the installation from files after the git clone (otherwise they are not available)
* it forces installation of pyqt4 (seems the new version of conda installs qt5 automatically)
* it fixes some error with n_processes due to change in the parameters in options
Still the build won't pass because there is an error with the tests. But I am getting this error locally too, so it is not travis. It is something about IPPP profiles. Could you try to see if you have the same error locally with nosetests?

Fixing some installation issues.

---

Dockerfile
ca_source_extraction/tests/test_demo.py

@agiovann I fixed the issue with the IPPP profiles. It was a result of a change in the cluster_start function.  It runs with 1 process during testing. The old test_demo function now produces very different results (different orders of magnitude) than before: maybe the testing file has changed? I incorporated the new values in the tests, so that they automatically pass, but some human eyes should look at the results of the old demo. Also, there is some slight difference in values between running the tests locally and on travis: that looks like numerical error, as I also get an error for division of zero. It would be interesting to compare to see whether there is slight variation with your local machine too.

Passing Tests: I hope.

---

README.md
caiman/source_extraction/cnmf/initialization.py
caiman/tests/test_demo.py

fixes some bug in HALS and adjusts its variable names to better align with the usual convention used in the codebase.
Also changed README.md to show the travis banner from simons not agiovann to account for the move of the repo.

fix HALS for initialization

---

README.md
caiman/base/movies.py
caiman/mmapping.py
caiman/motion_correction.py

Hi Andrea,
this works on my machine, can you test it please and check if it all works as its supposed to?
Thanks,
Ulf

Added support for SBX files

---

caiman/utils/visualization.py
demo_caiman_CNMF_3D.ipynb

This PR fixes the issues in function nb_view_patches3d and the demo using it

fix 3Ddemo

---

caiman/source_extraction/cnmf/merging.py
caiman/source_extraction/cnmf/temporal.py

This PR fixes memory issues by never ever ever ever representing A as dense matrix.

fix the 3 memory spikes

---

caiman/utils/visualization.py
demo_caiman_CNMF_3D.ipynb

Some small changes to speed up 3D plotting, which was quite slow for large datasets. Still not super-fast, but much better. Changing the z-layer with the slider can be very slow, but that's Bokeh's slowness in showing arrays as images, so not much we can do about that.
Also adjusted and fixed the 3D demo notebook.

speed up and fix 3D plotting

---

caiman/base/rois.py

Fixed typo with Exception causing failure

Update rois.py, fix typo

---

README.md
caiman/source_extraction/cnmf/online_cnmf.py

Hey,
I tried the OnAcId demo on a windows machine. Very nice.
1.I saw the installation procedure was outdated so did an update.
2.I also found an enoying error in the algortihm when I wanted to initialise more than 200 compounds. I (after some serious debugging) resloved this problem.
Keep up the good work

nasty bug and Windows installation instructions

---

setup.py

Changed setup.py to automatically find and include subpackages.  Resolves #99 
Changed package name to lowercase, to match PEP8 recommendations for package naming.

Changed setup.py to automatically find and include subpackages 

---

caiman/components_evaluation.py
caiman/mmapping.py
caiman/source_extraction/cnmf/cnmf.py
caiman/source_extraction/cnmf/spatial.py
caiman/source_extraction/cnmf/temporal.py
demos_detailed/demo_caiman_cnmf.py
use_cases/CaImAnpaper/compare_gt_cnmf_CNN.py
use_cases/data_minions/prepare_data_for_training_minions.py
use_cases/granule_cells/analysis_parallel_multisession.py

+ parallelized evaluation components
+ parallelized in memory efficient way residual computation
+ some general improvements in performance and code

improving memory efficiency and speed

---

.gitignore
1p_sim.py
caiman/cluster.py
caiman/components_evaluation.py
caiman/mmapping.py
caiman/motion_correction.py
caiman/source_extraction/cnmf/cnmf.py
caiman/source_extraction/cnmf/initialization.py
caiman/source_extraction/cnmf/map_reduce.py
caiman/source_extraction/cnmf/pre_processing.py
caiman/source_extraction/cnmf/spatial.py
caiman/source_extraction/cnmf/temporal.py
caiman/tests/comparison/comparison.py
caiman/tests/comparison/create_gt.py
caiman/tests/test_demo.py
demos_detailed/demo_caiman_cnmf.py
demos_detailed/demo_pipeline.py

Only thing to pay attention to is that threshold_Component needs to get a sparse matrix as input

New merging1photon multiprocessing

---

Jenkinsfile
environment.yml
test/linux-python2/Dockerfile
test/linux-python3/Dockerfile

New files for jenkins testing

---

demos_detailed/demo_caiman_cnmf.py

The way spyder feeds code chunks to the Python backend doesn't work with cell separators in the middle of a conditional, as far as I can tell.

Spyder breakpoints don't work in conditionals like this

---

caiman/behavior/behavior.py
caiman/tests/comparison/create_gt.py
caiman/utils/image_preprocessing_keras.py
pylint-all.sh

This also includes a diff that accidentally got left out of my prior pep8-aiming diffs

Script to run the linter on all py files. Not fast.

---

caiman/base/movies.py
demos/notebooks/demo_pipeline.ipynb

One of these was a known bug, the other is newly-discovered (Python 3 compatibility issue)

Pull two fixes into dev

---

caiman/source_extraction/cnmf/cnmf.py
caiman/source_extraction/cnmf/online_cnmf.py
demos/general/demo_OnACID_mesoscope.py
test_demos.sh

With this, test_demos runs clean again.

Fix some more little things on demos and past merges

---

caiman/utils/visualization.py

See https://github.com/flatironinstitute/CaImAn/pull/175 ; this is that PR adjusted for the dev branch.

Fix python2-python3 string/base64 encoding issues (in dev)

---

caiman/utils/visualization.py

User provided patch to make this work better.

Second fix for github issue 173 (master branch)

---

caiman/utils/visualization.py

User provided patch to make this work better.

Second fix for github issue 173 (dev branch)

---

caiman/mmapping.py

Remove removed parameter to save_memmap_join from a caller

---

CLUSTER.md
README.md

Starting a document on clustering options

Dev document clustering

---

environment.yml

Pin keras to 2.1.5

---

caiman/cluster.py
caiman/source_extraction/cnmf/map_reduce.py

motion_correction
cluster
Not comprehensive.
Signed-off-by: Mark Histed <mhisted@gmail.com>

make some switches away from stdout to logging

---

caiman/motion_correction.py

Signed-off-by: Mark Histed <mhisted@gmail.com>

limited doc changes

---

caiman/base/movies.py

Sometimes opencv fails to load AVI movies and fails silently, resulting in empty movie object. This patch will check if opencv successfully loaded movie, if not, it will use PIMS to load the movie. Need to add PIMS to requirements.

Update movies.py to add AVI backup loader

---

caiman/cluster.py
demos/general/demo_pipeline.py
demos/general/demo_pipeline_cnmfE.py
demos/notebooks/demo_caiman_cnmf_3D.ipynb
demos/notebooks/demo_motion_correction.ipynb
demos/notebooks/demo_pipeline.ipynb
demos/notebooks/demo_pipeline_cnmfE.ipynb

PR #227 is based on older sources; this PR recreates the intent of that PR against modern sources.

 recreate pr227 ipyparallel fixes

---

caiman/mmapping.py

adding the possibility to slice the data in all dimensions using the slice object

Memmaping slice

---

caiman/source_extraction/cnmf/cnmf.py
caiman/source_extraction/cnmf/map_reduce.py
caiman/source_extraction/cnmf/utilities.py

Got run_CNMF_patches to use CNMFParms

more changes to CNMFParms

---

caiman/source_extraction/cnmf/cnmf.py
caiman/source_extraction/cnmf/spatial.py
caiman/source_extraction/cnmf/utilities.py
caiman/tests/comparison/comparison.py

Merged function->method refactor into refactor main branch.

Refactor eo

---

caiman/base/movies.py
caiman/base/timeseries.py
caiman/motion_correction.py

This is to deal with issue https://github.com/flatironinstitute/CaImAn/issues/326

uniform way to write/read h5 files

---

caiman/source_extraction/cnmf/params.py
caiman/source_extraction/cnmf/spatial.py

Remove the lasso_lars_old method

Remove lasso_lars_old

---

caiman/base/rois.py

This is a model diff demonstrating how to document functions/methods that will make documentation-related tooling happier with our codebase. "make html" in the docs dir will help find other things that sphinx is angry about, but we have a lot of code to go through to tidy.
@epnev

Model diff: Fix docstrings for caiman/base/rois.py

---

setup.py

Please let this finish making its way through CI before merging

Caiman: Tweak C++ build flags for better OSX compatibility

---

caiman/utils/utils.py

Please do not merge this for me - I am using it to debug download_demo() in CI

Have download_demo() display the URL it's fetching, to make debugging failures easier

---

Dockerfile

This now successfully builds a Docker container with CaImAn inside (use the "caiman" conda environment).

Provide a modern Dockerfile

---

INSTALL-windows.md
README.md
caiman/base/movies.py
caiman/base/timeseries.py
caiman/motion_correction.py
caiman/source_extraction/cnmf/cnmf.py
caiman/source_extraction/cnmf/online_cnmf.py
caiman/source_extraction/cnmf/utilities.py

This small changes adds a good speedup to online. I also added another way of spelling the .tif extension (.TIFF) 
Not sure what happened in terms of merging, it included some other commits from Pat, probably because I merged without committing (my bad). @pgunn can you check that everything is OK? the only real changes here are 
- added an equivalent extinsion for tif files
- speed up online by ordering in the right directions array
Let me know!

Speed up online

---

caiman/mmapping.py
caiman/paths.py
caimanmanager.py
docs/Makefile
environment.yml
mypy.ini
readthedocs.yml

This adds a first batch of type annotations (PEP484) and a mypy configfile to the codebase. The more we annotate types, the more subtle (and not-so-subtle) bugs we'll find as we give mypy more to work with.
See also:
https://www.python.org/dev/peps/pep-0484/

Early type annotations

---

caiman/base/timeseries.py
caiman/cluster.py
caiman/mmapping.py
caiman/motion_correction.py
caiman/paths.py
caiman/source_extraction/cnmf/cnmf.py
caiman/source_extraction/cnmf/online_cnmf.py
caiman/source_extraction/cnmf/pre_processing.py
caiman/source_extraction/cnmf/spatial.py
caiman/source_extraction/cnmf/utilities.py

This adds more type annotations, and also refactors code across the codebase to use the new memmap_frames_filename utility function.

2019-03-25 Type annotations

---

caiman/source_extraction/cnmf/estimates.py
caiman/source_extraction/cnmf/merging.py
caiman/source_extraction/cnmf/spatial.py
caiman/tests/comparison/comparison.py
caiman/utils/stats.py
caiman/utils/utils.py

This PR utilizes sparse matrices during the computation of spatial footprint resulting in lower memory consumption and better speed

Sparse thresh

---

README-Distros.md
README.md
caiman/base/movies.py
caiman/base/rois.py
caiman/cluster.py
caiman/components_evaluation.py
caiman/mmapping.py
caiman/motion_correction.py
caiman/source_extraction/cnmf/cnmf.py
caiman/source_extraction/cnmf/estimates.py
caiman/source_extraction/cnmf/initialization.py
caiman/source_extraction/cnmf/map_reduce.py
caiman/source_extraction/cnmf/merging.py
caiman/source_extraction/cnmf/online_cnmf.py
caiman/tests/comparison_humans.py
caiman/tests/comparison_humans_online.py
caiman/utils/unused.py
environment.yml
use_cases/eLife_scripts/Figure_4-figure_supplement1.py
use_cases/eLife_scripts/figure_4_a_c_d_e.py
use_cases/eLife_scripts/figure_4_b.py
use_cases/eLife_scripts/figure_5.py
use_cases/eLife_scripts/preprocessing_files/Preprocess_CaImAn_batch.py
use_cases/eLife_scripts/preprocessing_files/Preprocess_CaImAn_online.py

This:
* adds more type annotations
* corrects the spelling of the word 'indices' across the codebase
* Avoids use of 'dict' as a variable name (as that's also a type, so it's confusing)
* removes a few functions that were not being used anywhere (and other cruft)
* has some very minor refactoring
* Adds some TODOs to think about for later work
* makes docs a little better in some places

Type annotation effort 2019-04-03

---

caiman/utils/visualization.py

plot_contours(): allow setting contour/label attributes

---

INSTALL-windows.md
Jenkinsfile
caiman/components_evaluation.py
caiman/source_extraction/cnmf/online_cnmf.py
caiman/tests/test_tensorflow.py
caiman/utils/utils.py
environment.yml

Trying out replacing the keras models with their tf counterparts. Results in terms of speed when running `demo_OnACID_mesoscope` on my mac laptop (no GPU) are not significantly different
More testing is needed.

remove keras (WIP)

---

caiman/base/movies.py
caiman/motion_correction.py
caiman/source_extraction/cnmf/utilities.py
docs/source/INSTALL-windows.rst

added support for slicing sbx files (scanbox). Now can motion correct directly from the sbx file

Sbx support

---

caiman/base/timeseries.py
caiman/source_extraction/cnmf/estimates.py
caiman/source_extraction/cnmf/online_cnmf.py
use_cases/NWB/demo_pipeline_NWB.py

renames variables according to the new [NWB Best Practices guide](https://neurodatawithoutborders.github.io/best_practices)

renaming for nwb best practices

---

caiman/source_extraction/cnmf/estimates.py
use_cases/NWB/demo_pipeline_NWB.py

cnmf.estimates.save_NWB error when saving estimates and rois fixed
timepoints, starting times and rates properly saved
NWB pipeline as ipynb added

cnmf.estimates.save_NWB error when saving estimates and rois fixed

---

caiman/gui/gui_pyqtgraph_layout.py

neurons/background/reset mode, scrolling effect, trace plotted

gui updated

---

GUI.md

If you're fixing a bug or introducing a new feauter make sure you run the tests by typing
```python caimanmanager.py test```
and
```python caimanmanager.py demotest```
include them in the folder 'caiman/tests/` and name them `test_***.py` so they can be included in our …

Add .mmap dependency to GUI.md

---

custom/post_analysis.py
custom/rois_Hendrik.py
demos/notebooks/demo_multisession_registration.ipynb
docs/source/CaImAn-Tips.md.rst
docs/source/Getting_Started.rst

Stuff that I did at the Flatiron. Includes 2 demo notebooks, a watershed ROI separation function, some documentation and parameter explanation for the wiki, and some post_analysis functions.

Hackathon2019

---

.style.yapf
.yapfignore
caimanmanager.py
environment.yml

This adds some plumbing for yapf, adds yapf to the environment file (so new people working with the codebase start getting it), and yapfs caimanmanager.py.

yapf initial

---

caiman/source_extraction/cnmf/online_cnmf.py
caiman/utils/utils.py
demos/general/demo_OnACID_mesoscope.py

Adding the capability to initialize the online algorithm with an estimate object 
- [ X ] New feature (non-breaking change which adds functionality)
Yes
```python caimanmanager.py test```
and
```python caimanmanager.py demotest```
Please describe any additional tests that you …

Estimates init online

---

caiman/source_extraction/cnmf/online_cnmf.py
caiman/utils/utils.py
demos/general/demo_OnACID_mesoscope.py

Small increase in speed for 2-photon online
Speed improvement
No 
```python caimanmanager.py test```
and
```python caimanmanager.py demotest```
include them in the folder …

Numba test

---

caiman/cluster.py
caiman/mmapping.py
caiman/paths.py
caiman/summary_images.py

Maybe it's better to go over files in small sets so we can make sure yapf doesn't remove formatting that makes the code more legible and drop in enable/disables of it as needed.

Some careful yapfing of some quiet files.

---

caiman/components_evaluation.py
caiman/gui/gui_pyqtgraph_layout.py
caiman/source_extraction/cnmf/estimates.py

Add 'add new neuron' and 'merge neurons' options to the GUI.
Click 'add new neuron' to select possible place that existsneurons not found by CNMF, click 'add single' to confirm.
Click 'merge neurons' and select several neurons that you want to merge, click 'add single' to confirm change.

gui modification

---

caiman/base/movies.py
caiman/base/rois.py
caiman/base/timeseries.py

Ran yapf on caiman/base/
Also fixed a weird phrasing.
Keeping this diff small because these files can change a lot.

yapfify caiman/base

---

caiman/gui/gui_pyqtgraph_layout.py
caiman/source_extraction/cnmf/cnmf.py
caiman/source_extraction/cnmf/estimates.py
use_cases/NWB/demo_pipeline_NWB.py

Fix GUI rotation 90 degrees problem;
Adjust GUI such that it is compatible with .nwb file

Dev fix gui

---

caiman/base/movies.py
caiman/components_evaluation.py
caiman/mmapping.py
caiman/summary_images.py

Running yapf on a few more files, and converting a few strings towards f-strings where it makes the code easier to read.

A bit more yapf, and some f-string conversions

---

caiman/base/movies.py
caiman/behavior/behavior.py
caiman/gui/caiman_gui.py
caiman/source_extraction/cnmf/online_cnmf.py
caiman/summary_images.py
caiman/tests/comparison/comparison.py
environment.yml

Results of more time with automated correctness tools

More code cleanups, a few things noted

---

caiman/base/movies.py
caiman/summary_images.py
demos/general/demo_caiman_basic.py
demos/general/demo_pipeline.py

+ Added support for efficiently removing baseline. 
+ Added  option to remove baseline in local correlation images
+ Updated demo_basic and demo_pipeline
Type
- [ X] New feature (non-breaking change which adds functionality)
ran python caimanmanager.py test
**not tested on all demos** -> on small laptop

Bl remove2

---

demos/notebooks/demo_OnACID_mesoscope.ipynb
demos/notebooks/demo_Ring_CNN.ipynb
demos/notebooks/demo_caiman_cnmf_3D.ipynb
demos/notebooks/demo_dendritic.ipynb
demos/notebooks/demo_motion_correction.ipynb
demos/notebooks/demo_online_CNMFE.ipynb
demos/notebooks/demo_pipeline.ipynb
demos/notebooks/demo_pipeline_cnmfE.ipynb
demos/notebooks/demo_seeded_CNMF.ipynb

This is an attempt to fix #722

Demos: Update notebook format

---

requirements.txt

1.1 can't open files made with NWB 1.3. Also now requirements.txt matches the environment.yml.

remove pynwb restriction

---

caiman/source_extraction/cnmf/estimates.py

Fixes #759
Fixes a number of assumptions that were made originally but are not true for this 1p workflow and may not be true in general:
* permit absence of cnn_preds
* permit absence of idx_components
* permit accepted_list or rejected_list to be present without the other
* fix bug where PlaneSegmentation does not write if Cn is not present
Also, updates the code a bit to be more robust to changes to the PyNWB API:
* use updated `add` method instead of `add_data_interface`
* use kwargs in create_plane_segmentation, so that code is more robust
to API changes
.
No. I'm not sure how to test in this case.
```python caimanmanager.py test```
and …

fix saveNWB for 1p data

---

caiman/source_extraction/cnmf/oasis.pyx
use_cases/LFADS-gang/trace_generation_and_deconvolution.py

This is not a proper PR, it is more of an invitation to change a line @j-friedrich. 
We need to solve the problem of the OASIS s_min parameter. The hardcoded value that I changed to close to 0 have created big troubles to some collaborators. It is not documented.  
- [ X] Bug fix (non-breaking change which fixes an issue)
- [ X] Changes in documentation or new examples for demos and/or use cases.
If you're …

momentary fix for OASIS s_min<0.5 issue and updated simulation

---

caiman/source_extraction/cnmf/cnmf.py
caiman/source_extraction/cnmf/estimates.py
caiman/source_extraction/cnmf/spatial.py
caiman/source_extraction/cnmf/temporal.py
docs/source/Handling_Movies.rst
docs/source/news.rst

The suggested changes fix some minor typos in the documentation and comments to improve readability and maintainabillity of the code. They have no effect on the production code itself.
Since this pull request does not fix a bug, it is made against the **dev** branch as suggested above.
The suggested changes fix some minor typos and have been tested with the spell checker `aspell`.

Fixed some typos in documentation and comments

---

docs/performance_guide.md

Would like each of your thoughts (and any changes you suggest) for this performance guide doc. Or even whether we should have something like this.

Caiman: draft of performance guide

---

caiman/source_extraction/cnmf/params.py
caiman/source_extraction/volpy/spikepursuit.py
caiman/source_extraction/volpy/utils.py
caiman/source_extraction/volpy/volparams.py
caiman/source_extraction/volpy/volpy.py
caiman/source_extraction/volpy/volpy_gui.py
demos/general/demo_pipeline_voltage_imaging.py

add volpy_gui;
delete temporal filtering in volpy
fix small bugs in caiman

Caim multifile

---

caiman/source_extraction/cnmf/utilities.py

Will merge this myself once it passes CI. This addresses #830 (at least partly).
Longer-term we should add some tests that exercise more of the codebase with pathlib paths.

add support to cnmf/utils to accept pathlib paths

---

caiman/source_extraction/volpy/mrcnn/model.py
caiman/source_extraction/volpy/spikepursuit.py
caiman/source_extraction/volpy/volparams.py
caiman/source_extraction/volpy/volpy.py
caiman/source_extraction/volpy/volpy_gui.py
demos/general/demo_pipeline_voltage_imaging.py

I updated VolPy GUI for correct Mask R-CNN outputs; add simple_thresh function; add some parameters for VolPy; fix some typos
```python caimanmanager.py test```
and
```python caimanmanager.py demotest```
include them in the folder 'caiman/tests/` and name them `test_***.py` so they can be included in our lists of tests.

update volpy gui; add simple_thresh function

---

caiman/source_extraction/cnmf/map_reduce.py

Catch some nans in input instead of failing silently

Catch some nans in input instead of failing silently

---

caiman/motion_correction.py

Add progress bar to the two main loops in `caiman.compute_metrics_motion_correction()`. This function can take a very long time to run -- often longer than the motion correction computations. These progress bars wrap the correlation calculation and optical flow calculation. 
It defaults to being disabled, and must be enabled using an environment variable (`ENABLE_TQDM` set to 'True'). 
Wrinkles:
- tqdm does not play well with loggers. Hence, within the for loops, if tqdm is enabled, I block out the loggers that print out which loop we are on. 
- tqdm tends to hiccup near stdout (e.g., print statements) and generate duplicates of the progress bar, unless you flush stdout first. Hence, before the two invocations of `tqdm` I added `sys.stdout.flush()` as discussed here: …

Add progress bar to compute_metrics_motion_correction()

---

caiman/base/movies.py

Make crop() function useful (with new name)

---

ISSUE_TEMPLATE.md

remove duplicate question in ISSUE_TEMPLATE

---

caiman/base/movies.py
caiman/base/rois.py
caiman/motion_correction.py
caiman/source_extraction/cnmf/cnmf.py
caiman/source_extraction/cnmf/online_cnmf.py
caiman/source_extraction/cnmf/utilities.py
caiman/tests/test_motion_correction.py
caiman/tests/test_utilities.py
demos/notebooks/demo_online_3D.ipynb

Main motivation: enable online processing of volumetric data
Side effects: 
- fixed a bunch of previously unnoticed bugs in motion correction, even for 2D data
- added faster OpenCV based gaussian-, maximum- and uniform-filters that support 3D
- added some tests for motion correction and the new filters
- added a small demo for online processing of 3D data 
Yes, 
```python caimanmanager.py test```
and
```python caimanmanager.py demotest```

 online processing of volumetric data

---

docs/source/conf.py

Change sphinx theme from classic to alabaster.
Mostly cosmetic change to modernize docs (but does modernize UI interactivity).
Have not run tests on this, not sure if we run tests on doc changes. Will run if answer is yes.

Change doc theme from classic to alabaster

---

caiman/source_extraction/cnmf/params.py

add check for rf and gSiz

---

caiman/cluster.py

cluster.py:setup_cluster() - cleanups, make 'single' backend

---

.github/workflows/run_tests.yml

Add continuous integration. This is running and working here: https://github.com/bendichter/CaImAn/pull/2
- All PRs should be made against the **dev** branch. The master branch is not often merged back to dev.
- If you want to get your PR out to the world faster (urgent bugfix), poke pgunn to cut a release; this will get it onto github and into conda faster
```python caimanmanager.py test```
and
```python caimanmanager.py demotest```
include them in the folder 'caiman/tests/` and name them …

add test workflow

---

caiman/source_extraction/cnmf/estimates.py

Fixes #1164 
Reproduced suspected bug, and fix was simple and worked and tested in demo.

fix estimates.play_movie so range var works

---

README.md

Explain anchor demos (cnmf/cnmfe) more clearly. Added link to video walkthrough of installation. Will add link to caiman central.

Readme update: explain how to work with demos

---

.github/workflows/run_tests.yml

Hoping this will fix #1312
Let's see how it goes

Test ci fixes

---

caiman/source_extraction/cnmf/params.py

CNMFParams: only nag people once for deprecation

---

caiman/source_extraction/cnmf/cnmf.py
caiman/source_extraction/cnmf/estimates.py

I spent a few hours figuring this out so it should be properly documented without having to run the notebook and figure out the exact types that are accepted.

Fix docstrings important for seeded initialization

---

caiman/base/movies.py

This removes a number of methods in caiman.base.movies that are not used in the caiman codebase.
We'll need to think carefully as to whether any of this was too aggressive - if users might be using any of these in their own code, or if they're things we generally might want to offer users as a matter of good form.
@kushalkolar

cleanup movie
