- ca_source_extraction/initialization.py
- ca_source_extraction/temporal.py
Hi Andrea,
this is a (~5x) faster version of HALS that alternates between updating shapes of all neurons and activities of all neurons, instead of looping over neurons in the outer loop. It avoids computation of the residual, thus being more memory efficient.
There has also been a bug in update_temporal_components, which returned the same g for groups of neurons.
Best,
Johannes
> Faster hals

- ca_source_extraction/map_reduce.py
This fixes an issue when the file name that is provided is a full path rather than just a file name
> Use file name instead of full path for patches log file

- use_cases/DeZeeuw/abadura_demo.py
I've noted a small bug in the function save_memmap_each (line 109 of file mmaping.py). I would suggest instead of: base_name+str(idx), to write instead: base_name+'{:04d}'.format(idx) . The reason is that after this function is called in the main code, you do: name_new.sort(). The problem is if you have the data contained in more than 10 tiff files, then you'll have a mismatch because the order will be the following: _1,_10,_11,.._19,_2,_20,_21,...,_3.. and so on.
> Save temp mmemap with four string digits

- caiman/components_evaluation.py
Newer versions of numpy are getting increasingly pedantic about the types of indices, to the point where they will throw a TypeError when a float is used as an index.
> Assert that shape argument to np.ones is an int

- caiman/base/movies.py
Sima sequences are read in sets of 1000 frames to avoid memory errors.
> Support large sima datasets

- caiman/utils/utils.py
- caiman/utils/visualization.py
This commit fixes two bugs:
1. Python 3 replaces `urllib2` with `urrllib.request` and `urllib.error`. `urllib.request.urlopen()` in Python 3 is equivalent to `urllib2.urlopen()` in Python 2.
2. Newer versions of the bokeh package don't use `vform()` & `hplot()`, instead they use `row()` and `column()`, which seem to work equivalently.
> Fix bugs with newer version of bokeh & Python 3's urllib

- caiman/summary_images.py
“print i*bin_size” is not supported in python 3
> support python3

- caiman/cluster.py
- caiman/source_extraction/cnmf/cnmf.py
- caiman/source_extraction/cnmf/initialization.py
- caiman/source_extraction/cnmf/utilities.py
Sorry for all the diffs: my editor deletes trailing spaces so a lot of lines are changed. Real changes are:
- In cnmf.py, l.199: send alpha_snmf to CNMFParams
- In cnmf.py, l.210: this check is not necessary anymore
- In initialization.py, l. 96: check if alpha_snmf is None here
- In utilities, l. 88, put alpha_snmf in the options['initial_params']
Now, alpha_snmf gets managed like any of the other parameters, i.e., put in the dictionary and used whenever necessary.
Cheers,
> Small fix to deal with alpha_snmf=None

- caiman/source_extraction/cnmf/pre_processing.py
The latest versions of numpy raise an IndexError rather than a warning when the shape of the indexing array does not match exactly the shape of the array itself.
> Avoid IndexError in get_noise_fft

- caiman/components_evaluation.py
- caiman/motion_correction.py
- demos_detailed/demo_pipeline.py
1. In the main pipeline I've added a call to the DF/F calculation function.
2. I started doing preparations for slice-based readout of files. This is important for cases in which a stack is interleaved with more than one spectral channel. The online pipeline already has support for this, I'm trying to bring this one on par. It's still not ready, though.
3. I commented out a line in `components_evaluation.py` which causes bugs (the first change below). It seems like no one is using this `significant_samples` variables, so I allowed myself to do it. It was hard to reproduce, so I can't tell exactly what caused the issue, but generally, the error was caused by the fact that sometimes `signifcant_samples__` contained a heterogeneous list of arrays and numbers, which meant that …
> Bugs squashed

- caiman/base/timeseries.py
The opencv cv2 module no longer contains a cv2.cv module, so I was getting an error trying to save a movie object as an AVI file. I propose a simple try/except block to handle both the old API and the new version. Works for me.
> Fix potential error in timeseries.py

- caiman/utils/visualization.py
Line 160 tries to call the power method on a `ndarray A.power(2)` however I got the error `AttributeError: 'numpy.ndarray' object has no attribute 'power'` and indeed the numpy docs: < https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.power.html > do not suggest that `ndarray` objects have a power method. You have to do `np.power(A,2)`. In my hands, if I run without patches mode, then the `A` matrix is a normal `ndarray` not a `coo_matrix` thus the line throws an exception. This PR will allow it to handle either case.
> Fix potential error in visualization.py

- caiman/components_evaluation.py
- caiman/mmapping.py
- caiman/motion_correction.py
- caiman/source_extraction/cnmf/map_reduce.py
- caiman/source_extraction/cnmf/pre_processing.py
- caiman/source_extraction/cnmf/spatial.py
- caiman/source_extraction/cnmf/temporal.py
Addresses some errors when running on windows.  Should have no significant effect on behavior.
`os.rename` will not delete an existing destination file, so delete it first.
`threading.Condition.wait` has a maximum timeout of 2^32 ms.  (However, it may be better and more efficient to use a timeout of `None` in these cases -- finite timeouts involve polling so will be slower.)
`fmax` is not defined for the old VC9 compiler python2 uses (python3 is fine), but the standard python `max` (which just expands to an inline ternary) looks like it should be fine in most cases.
> Fix some windows-specific calls

- SLURM/demo_pipeline.py
- caiman/utils/stats.py
Executing code during a library import is usually a bad idea (pydoc imports libraries while parsing code, as an example). Here I removed an instance of that, making a failure to find the numba library quiet. Also removed a bit of dead code from the slurm demo pipeline.
> Remove some dead code, also a spurious print that messes up pydoc

- caiman/utils/visualization.py
On python3, for better unicode compatibility, the core language thinks in terms of strings, but files on disk usually are represented as "bytes" (in python2 these are the same thing). Things are not transparently converted between the two. Additionally, python3's STRING.encode() method doesn't handle base64; that was pushed out into another library (that's included in the core language).
This diff adjusts our master branch for python3 compatibility.
> Fix python2-python3 string/base64 encoding issues

- Dockerfile
- Jenkinsfile
- caiman/components_evaluation.py
- caiman/mmapping.py
- caiman/source_extraction/cnmf/cnmf.py
- caiman/source_extraction/cnmf/initialization.py
- caiman/source_extraction/cnmf/online_cnmf.py
- caimanmanager.py
- demos/general/demo_caiman_basic.py
- environment.yml
- environment_python2.yml
- setup.py
- test/linux-python2/Dockerfile
- test/linux-python3/Dockerfile
- test_demos.sh
- use_cases/CaImAnpaper/compare_gt_cnmf_CNN.py
- use_cases/CaImAnpaper/online_testing2_bk.py
- use_cases/CaImAnpaper/online_testing2_bk_slurm.py
- use_cases/CaImAnpaper/slurm_mouse/mouse_slurm.sh
- use_cases/CaImAnpaper/train_net_cifar_curated_minions.py
This turns on selective testing of the demos on Linux and OSX as part of the CI pipeline.
It adds a subcommand to caimanmanager called "demotest" that runs the demos. I kept this separate from the nose tests because it's considerably slower and noisier.
For now Windows does not participate in this; I had to write a separate runner for Windows (no bash) and I haven't tested it (I will land it with a second diff). The Windows runner is included (same command, different backend).
> caimanmanager tests demos, CI tells it to (Linux + OSX)

- caimanmanager.py
This builds a codepath for caimanmanager to be able to do a check on a datadir installed from a Caiman install done with `pip install -e .`
> inplace support for caimanmanager's check function

- caiman/base/timeseries.py
- caiman/mmapping.py
- caiman/motion_correction.py
- caimanmanager.py
We only saw this overflow so far on Windows, but it may be possible in some circumstances on other platforms.
I'm going to follow up on this with a PR (or at least a bug report) to the numpy project (which should do this internally)
> Always promote shapes we pass to numpy.memmap to uint64 to prevent an overflow

- environment.yml
Adding PIMS to requirements for use as a backup AVI loader
> Update environment.yml, add PIMS

- caiman/base/movies.py
- caiman/motion_correction.py
- demos/general/demo_pipeline.py
There are now several options for treating boundaries when motion correcting:
- `border_nan=True` will set them to NaN as usual.
- `border_nan='min'` will set them to the minimum value of the frame
- `border_nan='copy'` will copy the first non-NaN entry.
Default choice is True although I would suggest changing it to the future.
> enabling non-nans in the borders during motion correction

- caiman/base/timeseries.py
- caiman/mmapping.py
- caiman/motion_correction.py
- caiman/utils/utils.py
We had a lot of code that would try importing tifffile and fall back to skimage if it failed. That should never happen anymore (conda takes care of it); this diff simplifies the code by removing the conditionality.
I also alphabetised some of the imports for files I touched to make them easier to look through.
> Remove fallback for missing tifffile, cleanup some imports along the way

- Jenkinsfile
- demos/general/demo_OnACID.py
- demos/general/demo_OnACID_mesoscope.py
- demos/general/demo_behavior.py
- demos/general/demo_caiman_basic.py
- demos/general/demo_pipeline.py
- demos/general/demo_pipeline_cnmfE.py
This diff does some mild trickery to get our demos running the same way under the program model and the notebook model.
As a notebook, each cell is "pasted over" to the interpreter outside of function context. In this case, the cell boundaries are crafted so there is a main() function that just does a pass. In this case, Spyder manages multiprocessing so we don't need main() block protection.
As a program, it's parsed in a way where there's a long main() function that is invoked (with __main__ gating) at the end. This gating protects the code on platforms where forkserver/spawns would otherwise do a forkbomb, getting them to behave correctly (Windows was particularly affected).
Provided we maintain the demos in this form, this is a viable path forward that entirely eliminates …
> Modify demos so they always run the same cell-based or as programs.

- caiman/source_extraction/cnmf/cnmf.py
- caiman/source_extraction/cnmf/utilities.py
There are two new methods for the cnmf object:
- `cnmf.evaluate_components` will call `estimate_components_quality_auto`
- `cnmf.filter_components` will adjust `idx_components` and `idx_components_bad` based on new threshold values without re-computing the metrics. It uses `select_components_from_metrics` which unfortunately calls the cnn classifier every time.
The various threshold parameters can be passed in as inputs. If they're not provided defaults values are being read from `cnmf.options['quality']` which is newly added.
> add quality evaluation in the object

- caiman/source_extraction/cnmf/cnmf.py
using the de-noised trace for the residual computation seemed to work better then the noisy one.
sufficient statistics calculation was off by one frame. Now `minibatch_suff_stat=0` corresponds to no lag, i.e. taking the last frame.
> bug fixes for online processing

- caiman/source_extraction/cnmf/cnmf.py
- caiman/source_extraction/cnmf/utilities.py
Nosetests were failing against ground truth because of the new CNMFParms class. The object instances were distinct, so the == operator was returning false. To fix this, we just needed to implement the __eq__ function in CNMFParms class.
> fix failing nosetests with new CNMFParms class

- caiman/source_extraction/cnmf/cnmf.py
- caiman/source_extraction/cnmf/estimates.py
- caiman/source_extraction/cnmf/initialization.py
- caiman/source_extraction/cnmf/map_reduce.py
- caiman/source_extraction/cnmf/params.py
- caiman/utils/visualization.py
- demos/general/demo_pipeline_cnmfE.py
updates code for 1p background.
No matter whether using patches or not the following documentation in the demo now actually holds
Added the option to return b and W also when using patches.
If the full rank background is returned, than as sparse b and dense f, with smart computation of b that avoids to ever use a dense pixel x pixel matrix.
Updates some visualization functions to work with the ring model background.
> 1p background

- caiman/source_extraction/cnmf/online_cnmf.py
more efficient computations in `get_candidate_components`
fix batch update of sufficient statistics to use `min(update_freq, minibatch_shape)`
> speed up OnACID by ~15% if testing to add multiple components

- caiman/tests/comparison/comparison.py
On OSX, any nosetests code that brings up a GUI window will cause a segfault if there's no Windowserver available. This issue was breaking OSX in CI.
To find the relevant code:
1) I set the DISPLAY environment variable to an invalid value, causing the Qt library to segfault when it tried to do GUI things, and
2) I used the technique described here: https://blog.richard.do/index.php/2018/03/how-to-debug-segmentation-fault-in-python/
to get a backtrace from that segfault, giving me the point in our code that was actually trying to bring up a GUI window.
> Remove some code that would bring up graphical windows under nosetests

- caiman/utils/utils.py
On trying to save the results using `cnm2.save()`, I got the following error:
```
ValueError                                Traceback (most recent call last)
<ipython-input-108-b2ac98e98e5a> in <module>
3 if save_results:
4     import time
----> 5     cnm2.save(fnames[0] + time.strftime("%Y_%m_%d_%H_%M") + 'analysis_results.hdf5')
h:\caiman\caiman_git\caiman\source_extraction\cnmf\cnmf.py in save(self, filename)
603 
604         if '.hdf5' in filename:
--> 605             save_dict_to_hdf5(self.__dict__, filename)
606         else:
607             raise Exception("Filename not supported")
h:\caiman\caiman_git\caiman\utils\utils.py in save_dict_to_hdf5(dic, filename)
357 
358     with h5py.File(filename, 'w') as h5file:
--> 359         recursively_save_dict_contents_to_group(h5file, '/', …
```
> hdf5 recursive group save: Add support for missing np.int32

- caiman/source_extraction/cnmf/utilities.py
I got an error for an attempt to assign to a tuple here:
```py
dims[0] = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
dims[1] = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
```
> Load AVI: Fix get_file_size() assigning to tuple

- caiman/mmapping.py
Hoping to fix issue #448 - believe we're going above the bounds of uint32 and numpy isn't doing type promotion for us. This sprinkles in a cast to np.uint64 and also improves logging for the code that's breaking
> mmapping: explicit type promotions to avoid overflow

- caiman/utils/utils.py
Small change that should be a no-op: make import of urllib no-longer-conditional (was that way for Python2 compatibility). Update comment to point at Python3's urllib docs.
> Remove conditional import that was for Python 2/3 compatibility

- caiman/utils/utils.py
Added a workaround to the permission error. This should solve issue #457. However, we might want to find a more permanent solution storage that would not block the urlreq. I did not propagate the changes to master since I do not know if you are OK with this patch.
> workaround to urllib permission error

- caiman/utils/utils.py
This is meant as a better fix for #457 . The old endpoint was pointing at a CloudFront cache which has anti-abuse features that sometimes considered API-like web requests invalid and returned 500. Dylan set up a direct DNS name for us that points right at our users service (but otherwise has identical semantics to users.flatironinstitute.org) so that won't be a concern anymore.
> Change domain for datafiles hosting to a direct (non-Cloudfront) endpoint

- caiman/mmapping.py
Not 100% sure this isn't just signed-versus-unsigned, but I suspect that's not it.
If this ever proves insufficient, could use np.ulong instead, but that's less predictable and I'm reasonably sure long is 64-bit on most 64-bit architectures we'll encounter. Could even do np.ulonglong but again, that's not well defined.
> mmapping: Explicit cast to np.uint64 to handle platforms where int is not already 64-bit (overflow)

- caiman/base/movies.py
- caiman/source_extraction/cnmf/utilities.py
Add support for NWB files that are actually HDF5 files.
This is a stopgap while we work on a more robust backend-agnostic pynwb importer.
> NWB support

- caiman/tests/comparison/comparison.py
Recent versions of numpy changed the default value for allow_pickle in np.load() to False; this overrides the new default
> Adapt to new default value for a parameter to np.load()

- caiman/source_extraction/cnmf/map_reduce.py
@epnev There was one additional place where there NaNs were causing problems -- in the NMF on the background temporal components. Filtering out components with NaNs fixes this problem, which I think is OK since these components aren't meaningfully contributing to background anyways.
> NaN check in background component decomposition

- caiman/cluster.py
Addresses #519 
@pgunn , @epnev 
Whitespace removal was PyCharm's decision (with my current settings), though I kept that in there, because it's harmless.
> Setup cluster ignore flag

- caiman/source_extraction/cnmf/params.py
A draft addressing #526 
@epnev current iteration looks like:
```python
from caiman.source_extraction.cnmf.params import CNMFParams
print(CNMFParams())
```
```
CNMFParams:
data:
{'decay_time': 0.4,
'dims': None,
'dxy': (1, 1),
'fnames': None,
'fr': 30,
'var_name_hdf5': 'mov'}
spatial_params:
{'block_size_spat': 5000,
'dist': 3,
'expandCore': array([[0, 0, 1, 0, 0],
[0, 1, 1, 1, 0],
[1, 1, 1, 1, 1],
[0, 1, 1, 1, 0],
[0, 0, 1, 0, 0]]),
'extract_cc': True,
'maxthr': 0.1,
'medw': None,
'method_exp': 'dilate',
'method_ls': 'lasso_lars',
'n_pixels_per_process': None,
'nb': 1,
'normalize_yyt_one': True,
'nrgthr': 0.9999,
'num_blocks_per_run_spat': 20,
'se': None,
'ss': None,
'thr_method': 'nrg',
'update_background_components': True}
temporal_params:
{'ITER': 2,
'bas_nonneg': False, …
```
> CNMFParams repr

- caiman/source_extraction/cnmf/spatial.py
This is a possible solution to the problem of when videos have pixels that are set to 0 across time, such as when a mask is applied to all frames. Removes components with nans and also skips pixels that are 0.
> Zero pixels issue

- caiman/source_extraction/cnmf/initialization.py
the hals init routine was yielding NaN corrupted data in some CNMF runs I was doing, this stabilized it
> add epsilon in HALS routine to prevent NaNs

- caiman/source_extraction/cnmf/online_cnmf.py
Latest update for supporting different classifiers breaks if sniper_mode is False, due to self.loaded_model, self.tf_in and self.tf_out. Fixed by setting those to None for sniper_mode=False.
> Run OnAcid without sniper_mode

- caiman/source_extraction/cnmf/cnmf.py
- caiman/source_extraction/cnmf/merging.py
- caiman/source_extraction/cnmf/params.py
Currently, when performing CNMF, during the refinement stage overlapping components are merged if their correlation is above a certain threshold. This leads to situations like below, where two adjacent neurons whose activity is highly correlated can start off as two components but become merged into one component:
In this case, splitting this single component back into two after-the-fact is a difficult problem. If the expected area of a neuron is known, this can be avoided by preventing components from being merged if the resulting merged component would have an area that's too large, even if the original components are highly correlated. This pull requests adds an optional `max_merge_area` parameter to do this. In the situation shown above, this allows us to have two components …
> Add a max_merge_area parameter for preventing the merging of components if the merged component's area is too large

- caiman/source_extraction/cnmf/params.py
- caiman/utils/utils.py
This adds a standard function in utils that tries various methods to get some notion of the version of caiman that's installed. Parsing the output is still the user's responsibility.
> Add standard function to get (some muddled notion of) caiman version

- caiman/source_extraction/cnmf/estimates.py
- caiman/utils/visualization.py
- demos/notebooks/demo_pipeline_cnmfE.ipynb
Add new visualizations for components and correlation pnr images.
hv_view_patches and hv_view_components are added as drop-in replacement for nb_view_patches and nb_view_components. nb_inspect_correlation_pnr are added following naming convention.
New feature (non-breaking change which adds functionality)
```python caimanmanager.py test```
success
```python caimanmanager.py demotest```
failed with following message:
> runcmd[/home/bendog/caiman_data/test_demos.sh]
> xvfb-run command not found
> Error in runcmd
> add visualizations based on holoviews

- caiman/source_extraction/cnmf/estimates.py
Using the `manual_merge` function leads to the following error in Python 3.7.3 due to `computedA` missing a  second dimension:
```
ValueError: shape mismatch in assignment
```
This is fixed by adding the missing dimension.
> Fix 'shape mismatch in assignment' error in manual_merge function

- caiman/base/movies.py
- caiman/base/rois.py
- caiman/base/timeseries.py
- caiman/gui/gui_pyqtgraph_layout.py
- caiman/source_extraction/cnmf/online_cnmf.py
- caimanmanager.py
- environment.yml
This adds an (undocumented) subcommand to caimanmanager that runs nosetests with coverage enabled. It also adds coverage to environment.yml so source builds include it. I did not add it to the feedstock because there's no point in running this test outside of a source build.
Note as well that coverage imposes additional rules on python that restrict array resizing, causing caiman code to throw an error. We probably should look into this. The error looks like this:
```
Traceback (most recent call last):
File "/mnt/home/pgunn/miniconda3/envs/caiman/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "/mnt/home/pgunn/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/tests/test_onacid.py", line 54, in test_onacid
demo()
File …
```
> Add a caimanmanager command to include coverage

- environment.yml
To deal with the latest releases of tifffile not supporting our sample tifffiles (and the new library you'd install currently not having a conda package so we can't just add it to the environment.yml), this pins tifffile at 0.15.1.
Upstream issue is filed against the feedstock:
https://github.com/conda-forge/tifffile-feedstock/issues/32
> Pin to earlier tifffile before upstream breakage

- caimanmanager.py
On OSX (only), the tests subcommand of caimanmanager (which invokes nosetests) was hanging in multiprocessing code.
This diff:
A) Adds --verbose to the invocation of nosetests so it's easier to see which test failed
B) Has caimanmanager set the environment variables we document for OSX that tell OpenCV and other numeric code to serialise calls through veclib into platform libraries that are not thread-safe so this won't come up
In theory some future version of OSX may make those platform libraries thread-safe, after which we'll be able to revert part B.
> caimanmanager: always verbose for nosetests, set env vars for safe multiprocessing

- README.md
- caimanmanager.py
- environment.yml
- test_demos.sh
This diff:
* Notes that VolPy requires an optional install of Keras to function
* Removes keras from environment.yml
* Adds the volpy demo to things that the test commands in caimanmanager will never run
It should be followed up with a diff to the feedstock to take keras back out from the binary builds.
> volpy: keras is now an install optional

- caiman/mmapping.py
This fixes (removes) an accidentally included parameter to save_memmap_join() that's only valid for the other save_memmap... calls. This issue was reported on gitter.
> Fix issue with save_memmap_join() reported on gitter

- caiman/base/movies.py
- caiman/base/timeseries.py
- caiman/source_extraction/cnmf/utilities.py
According to [OME-TIFF spec](https://docs.openmicroscopy.org/ome-model/6.0.1/ome-tiff/specification.html) `.ome.btf` is valid, and, in my experience, common. Since [tifffile](https://pypi.org/project/tifffile/) supports OME-TIFF, I've modified logic so CaImAn supports `.btf` files.
I've tested the motion correction pipeline on a very small `.btf` file and it seems to work properly. Unfortunately, most of my files are 70GB+ of `uint16` bigtiffs, so reading in as float32 means my computer ran out of memory. I plan on trying my hand at removing `asarray` & doing stream processing, but if someone at flatiron is already doing this please let me know so I don't duplicate effort! Thanks
> Use tifffile for .btf files

- caiman/source_extraction/cnmf/estimates.py
For Issue 465 parameter labels were added to contour plots (https://github.com/flatironinstitute/CaImAn/issues/465). However, instead of the intended `min_SNR` (which is the actual threshold) it displays `SNR_lowest`. This PR fixes that issue.
Not tested.
> update estimates.py -- fix params in contour plotters

- caiman/base/movies.py
- caiman/base/timeseries.py
- caiman/source_extraction/cnmf/utilities.py
In our lab we make extensive use of the more modern Matroska container (MKV) for videos, mostly containing FFV1 or VP9-encoded material. The new Miniscope v4 DAQ software as well as the PoMiDAQ Miniscope DAQ software are also either using MKV as default or supporting it in combination with FFV1 as an option.
Fortunately, making CaImAn support loading video data from MKV files natively is a very trivial change, so with this patch it can load data generated in the MKV format directly without any conversion.
All Linux distributions understand MKV natively (via GStreamer or FFmpeg) and Windows supports this format out of the box since Windows 10 as well.
Yes, it doesn't break anything and works fine for our files (CaImAn loads and analyzes them)
Thanks for considering!
> Support loading videos from MKV containers

- caiman/base/movies.py
- caiman/motion_correction.py
- caiman/source_extraction/cnmf/params.py
- caiman/source_extraction/cnmf/spatial.py
- caiman/source_extraction/cnmf/utilities.py
Addresses issue #749 by properly loading 3D *.nwb files and using `load_iter` instead of `load` during motion correction for memory efficiency. 
Fixes # (749)
```python caimanmanager.py test```
and
```python caimanmanager.py demotest```
include them in the folder 'caiman/tests/` and name them `test_***.py` so they can be included in our lists of tests.
> proper loading of 3D .nwb files (solves #749)

- caiman/base/movies.py
- caiman/utils/utils.py
- caimanmanager.py
This:
A) removes an unused function (there's a few more we should probably just let live in the git history)
B) Adds to utils a get_tempdir() that will eventually be used to hold all temporary files belonging to the current run. This is controllable with the CAIMAN_TEMP environment variable, and will default to caiman_data/temp/; the current behaviour (which I consider antisocial and which people have occasionally grumbled at me about; leaves cruft in cwd) can be maintained by setting it to '.'   -- note that this will also make it easier to manage (but not necessarily entirely safe, depending on threading choices) running multiple copies of Caiman at once, differentiated only by env vars. It will also be friendlier to docker and other environments where parts of the exposed filesystem …
> dev: remove some old crift, move towards better handling of temporary files

- CHANGELOG.txt
- caiman/base/movies.py
- caiman/base/timeseries.py
- caiman/mmapping.py
- caiman/motion_correction.py
- caiman/paths.py
- caiman/source_extraction/cnmf/cnmf.py
- caiman/source_extraction/cnmf/online_cnmf.py
- caiman/tests/test_demo.py
- caimanmanager.py
This:
1) Adds a CHANGELOG.txt
2) Reimplements, on user request, the ability to have CaImAn not leave files in the current working directory for its scripts. This is not enabled by default right now, but it passes tests when it is both enabled and when the tests are run from a readonly directory.
I hope to eventually switch this to being enabled by default, but not in 1.9.0.
Longer-term I hope to make a storage manager module that handles everything relating to filenames; it might also pull a lot of other file handling logic out of the rest of the codebase into a central place.
This PR is primarily intended to document the change, but any commentary on it before it lands in dev is welcome.
> storagedir

- Dockerfile
The current implementation of the dockerfile clones the repository directly from github, from flatironinstitute's repository.
However, whenever someone forks the repository (or works on a specific branch) the resulted image will contain a different code than intended.
Relevant documentation for creation of a docker image in a project:
https://docs.docker.com/language/python/build-images/
The new solution copies the repository's files directly from the currrent folder.
Ran
```python caimanmanager.py test```
successfully.
> dockerfile copy repository from local

- caiman/base/movies.py
Updates the load function so it uses memory more efficiently when loading a large tiff file stored as a single pagefile.
When loading a large tiff stored as a single pagefile movies.load() will load the entire tiff file into each active processor. This tends to use up all the available memory. 
In tffl.asarray() set out = 'memmap'    This uses memory more efficiently but is still slow. 
- [* ] Bug fix (non-breaking change which fixes an issue)
Yes, test and demotest
> Updates load in movies.py

- caiman/source_extraction/cnmf/spatial.py
Using normalization within sklearn.linear_model.LassoLars() is deprecated and prints many warnings which slow down refitting for the cnmf. I followed sklearn's suggestion to use a pipeline with StandardScaler instead.
caiman used a deprecated form of normalization within sklearn.linear_model.LassoLars(). The deprecation warnings print in the command line and slow down computation or freeze the IDE (spyder). 
To fix this I followed sklearn's suggestion to use StandardScalar within a pipeline to normalize the data and set normalization=False within LassoLars(). 
- [ *] Bug fix (non-breaking change which fixes an issue)
Yes, test and demotest
> fixed deprecated normalization in spatial.py

- README.md
- caiman/source_extraction/volpy/README.md
- caiman/source_extraction/volpy/mrcnn/config.py
- caiman/source_extraction/volpy/mrcnn/model.py
- caiman/source_extraction/volpy/mrcnn/utils.py
- demos/general/demo_pipeline_voltage_imaging.py
Mask R-CNN in VolPy previously only worked on tensorflow 1 and needed users to install keras. Now it worked on tensorflow2.4.1.
Fixes # (887, 963)
> volpy maskrcnn compatible tensorflow 2.4.1

- caiman/source_extraction/cnmf/estimates.py
Changes it so on initial use after reconstruction of cnmf object from memory, component viewers will work, as discussed here:
https://github.com/flatironinstitute/CaImAn/issues/967
Also fixing problems with PR 968 (I was working from the wrong base branch so PR became spaghetti mess):
https://github.com/flatironinstitute/CaImAn/pull/968
Fixes #967
- [ x] Bug fix (non-breaking change which fixes an issue)
I made sure that the viewers worked in a demo notebook that initiated a fresh cnmf instance from memory. 
I ran test/demotest which both succeeded.
> fixed nb viewer (hv, nb, and nb3d) check on empty R

- caiman/motion_correction.py
Added support for other values of border_nan in tile_and_correct_3d() and MotionCorrect.apply_shifts_movie() when using piecewise rigid motion correction.
Previously, when using piecewise rigid motion correction on 3D data, the border was always filled with `0.0` regardless of the value of `border_nan` set. This change results in `np.nan` in the border when `border_nan = True`, copying of the border values when `border_nan = 'copy'`, and filling with the minimum of the image when `border_nan = 'min'`. The previous behavior is used when `border_nan = False`.
Both
```python caimanmanager.py test```
and
```python caimanmanager.py demotest```
run and report success.
> 3D Piecewise Rigid Motion Correction Respecting value of border_nan

- docs/source/Getting_Started.rst
`estimates.C` refers to the temporal component, not background right?
> fix typo in docs

- caiman/base/movies.py
- caiman/base/timeseries.py
This pull request fixes the cropping method in the movie class, which gives a ValueError when run (e.g., "ValueError: could not broadcast input array from shape (1000,340,348) into shape (1000,390,388)"). The changes make it so the cropped movie is returned and not cropped inline.
A second edit also allows timeseries.save to save .avi files using the FFV1 codec, which a lossless codec, resulting in a much smaller file size.
It had one error running python caimanmanager.py test: the parallel test. I'm not sure what the issue is, since my edits are minor and shouldn't affect the parallel processing. I've recently been getting parallel errors with my computer (prior to any edits of the code), though, so that's likely the issue.
The demotest ran successfully.
> Fix cropping method and add ability to save compressed .avi files with the FFV1 codec

- caiman/source_extraction/cnmf/utilities.py
Tiff files created in append mode raise an IndexError when saving the memmaped motion correction movie. This is due to `cnmf.utilities.get_file_size()` returning the wrong dims.
Example: 
```python
cm.source_extraction.cnmf.utilities.get_file_size("/home/kushal/tiff_mcorr_issues/ap1_1_pt_5a.tif")
>>> ((216,), 270)
cm.source_extraction.cnmf.utilities.get_file_size("/home/kushal/tiff_mcorr_issues/ap1_1_pt_5a_single.tif")
>>> ((270, 216), 27090)
```
Tiff files created in append mode are created like this:
```python
tif_writer = tifffile.TiffWriter(output_path, bigtiff=True, append=True)
for frame_ix in range(n_frames):
tif_writer.write(frame)
```
Tests passing on my end.
Stack trace without the fix:
```python
IndexError                                Traceback (most recent call last)
Input …
```
> Fix cnmf utils get file size for tiff files created in append mode

- caiman/source_extraction/cnmf/map_reduce.py
- Fixed a docstring typo, `CNMFParms` -> `CNMFParams`.
- Adapted the docstring of `map_reduce.run_CNMF_patches` to match the actual function signature
Note: Since I do not know the details of this function, I could not write the full docstrings myself. I opted to have a complete and up-to-date docstring, and left TODO notes for the arguments that were not documented.
Not tested, as it is just a trivial change in the docs.
> Update docstrings and fix typos in `run_CNMF_patches`

- caiman/source_extraction/cnmf/spatial.py
minor change, the latest sklearn v1.2 that just released deprecated the `normalize` kwarg for `LassoLars`, it just produces a massive stream of warnings during CNMF (they can be disabled but it'll be removed by v1.4 so might as well fix it?)
```python3
/home/kushalk/python-venvs/mescore/lib/python3.10/site-packages/sklearn/linear_model/_base.py:117: FutureWarning: 'normalize' was deprecated in version 1.2 and will be removed in 1.4. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.
warnings.warn(
```
not exactly sure which tests should be used, I ran `nose2` in the root dir with both `nose` and `nose2` …
> sklearn deprecation, remove `normalize` from LassoLars

- README.md
Added links to Andrea's talks/workshops and a relatec packages section.
Andrea's Open Neuroscience talk is probably the best introduction to CaImAn, it's a great starting point because the papers can be quite dense and scare-off users. I think it'd be useful to highlight that talk earlier in the README if you agree.
> add related packages and videos to README

- caiman/base/movies.py
add an "embed_opencv" backend to movie.play such that the movie is played within the notebook, not a new window (which leads to a crashing kernel when running e.g. in the cloud)
uses opencv and IPython.display. Surprisingly, (on my MacBook) this is faster than the opencv default of displaying in a separate window
Yes
```python caimanmanager.py test```
and
```python caimanmanager.py demotest```
> Embed opencv

- docs/source/GUI.rst
removes the reference to the old mesmerize in the docs, updated it with the new libs instead
> remove reference to old mesmerize in docs

- caiman/source_extraction/cnmf/online_cnmf.py
numpy 1.22 (over a year ago) completely reworked np.percentile(), causing our old way of calling it to no longer be valid (that way may have never been intended).
Here I flatten the input array down with np.ravel() before passing it in, which seems to give the same result that 1.21 did on the non-flattened array.
I am very unsure about this fix (and we may need to visit other uses of np.percentile() to see if they need adjustment too).
> cnmf/online_cnmf.py:OnACID.initialize_online(): Fix call to np.percentile()

- caiman/source_extraction/cnmf/online_cnmf.py
adding some docstrings and comments to OnACID
> OnACID docs

- caiman/base/movies.py
- caiman/source_extraction/cnmf/utilities.py
- demos/notebooks/demo_online_cnmfE.ipynb
A few minor tweaks to the branch.
- Some spacing issues in movies.py (there were tabs!). Also, some indendentations weren't lining up properly the logic was awry -- please check to be sure I got it right. 
- Added movie viewer in the cnmfe_online demo notebook to be sure `load()` works, and added a logger message and set logger to debug temporarily while we work on this -- in particular added log message in movies.py near concern with use  `dims` when it could be broken (before offloading to pims).
- Changed criterion for offloading to pim from `==0` to `<=0` in the three places `VideoCapture()` is used, because opencv returns `-1` as a dimension when it is broken sometimes, so this covers all our bases.
> Dev load pims fallback

- caiman/utils/visualization.py
Adds functionality to visualize overlapping patches that split up field of view for motion correction and cnmf for parellelization. Useful when picking different spatial parameters (`rf/stride/gSig/gSiz` for cnmf, and `strides/overlaps` for motion correction).
Thanks to @kushalkolar (mesmerize) for idea of `quilt` name, as `patches` is already used for viewing spatial contours. 
Fixes #1116 
I ran the tests there are no new errors introduced in dev branch.  I have tested the plotting functionality fairly extensively, have not yet added new tests to `caiman/tests`
> Adding quilt viewer to visualize how FOV is broken up into patches

- caiman/source_extraction/cnmf/estimates.py
- caiman/utils/visualization.py
- demos/notebooks/demo_caiman_cnmf_3D.ipynb
- demos/notebooks/demo_online_3D.ipynb
Updating visualization tools to handle updated bokeh as discussed in issue #1127. Basically two problems: the way it handled y origin was changed, and `plot_height` was deprecated. Also, I fixed an unrelated check for `None` that was throwing an error. 
Fixes #1127 
This is not yet finished, as discussed at the issue `nb_view_patches3d()` is still acting weird and I'm not sure how to put in the simple fix. It is probably something really simple I'm missing :smile: 
- [ X] Bug fix (non-breaking change which fixes an issue)
> updated vis tools to work with new bokeh

- _buildhelper_cython.py
- buildhelper_cython.py
- pyproject.toml
- setup.py
This adds the needed additional files for PEP-517 compliant pip plumbing.
The practical impact of this is little:
* future-proofing our setup (in case the current tools eventually stop supporting old-style setup.py)
* For the very few people who build with environment.yml and then pip install, it is used and re-enables the `-e` flag
* It may make the (not encouraged but still sort-of-supported) pip install path used as a last resort and by colab a bit more efficient
In the longer-term we'll want to follow up on this by moving more of the fields from "dynamic" values defined in setup.py into residing just in the toml - I don't *ever* want to do that with the version value, but the other fields are good candidates for that). I'm not doing that now because I'd like to sit in the middle for …
> pyproject / PEP-517

- caiman/source_extraction/cnmf/estimates.py
- caiman/utils/visualization.py
- demos/notebooks/demo_caiman_cnmf_3D.ipynb
- demos/notebooks/demo_online_3D.ipynb
As far as I can tell, fixes the residual issues brought up in #1127 and previous PR #1129 . The problem was that images were inverted in ways I didn't notice, and this was percolating into almost every visualization function. I think it is now fixed in all tools (2d and 3d). 
[X] Bug fix (non-breaking change which fixes an issue)
Yes against test and demotest, and I also tested with the following pipelines:
demo_pipeline
demo_pipeline_CNMFE
demo_caiman_cnmf_3D
demo_online_cnmfE
demo_online_3d
These all seemed to work well!
@j-friedrich it would be helpful if you tested that this is indeed reasonable (esp in `demo_caiman_cnmf_3D.ipynb` which is where thigns broke before: I think `axis=2` is working well now too for the 3d component viewer with max projection, which is really nice, as that …
> Bokeh plotting 2->3 fix second (final?) round

- caiman/base/movies.py
- environment-minimal.yml
- environment.yml
- requirements.txt
- requirements_gpu.txt
This removes z5py as a dependency, swapping in zarr (which is also available in pypi, so it also replaces the conditional imports with a static import)
> Switch from the z5py library to the zarr library

- caiman/caimanmanager.py
- caiman/utils/utils.py
This fixes a small bug in how caiman versions are calculated/reported (and is paired with some changes in the conda-forge plumbing). It's very low-impact (the fallback logic was being used routinely and this will make that less so, and the version string is not used for much).
> fix version string

- demos/notebooks/demo_pipeline.ipynb
- demos/notebooks/demo_pipeline_cnmfE.ipynb
Release 1.10 notebook updates included images in notebooks with relative paths that worked when running from source, but not from caiman_data. Added absolute links to images on github to fix so images would render regardless of working dir.
> Fix links to images in notebooks

- demos/notebooks/demo_pipeline.ipynb
- demos/notebooks/demo_pipeline_cnmfE.ipynb
Expected to go out in next patch (with image link fix #1261 ). Improved formatting of estimates description. Improved discussion of $\Delta F/F$.  Added example plot of DFF trace. 
Still need to look over a couple of things wrt DFF, e.g., would like to fix infinite loop (#1262 ).
> Minor tweaks in notebooks for next 1.10 patch

- caiman/base/movies.py
- caiman/cluster.py
- caiman/source_extraction/cnmf/deconvolution.py
- caiman/source_extraction/cnmf/estimates.py
- caiman/source_extraction/cnmf/initialization.py
- caiman/utils/nn_models.py
- docs/source/Installation.rst
- docs/source/Overview.rst
- docs/source/conf.py
- docs/source/core_functions.rst
- docs/source/index.rst
This PR is an attempt to fix some of the sphinx rendering issues - namely the issues with the core functions having sections but no functions/methods showing up.
It does NOT fix all the issues we're aware of, particularly the ReadTheDocs broken links for non-function-reference stuff, but those will take some thought and a redesign.
At least with the local rendering, things look good. This can be reproduced with a source tree by:
1) activating whatever environment is used (I use `caibuild` for my compiled caiman environment)
2) doing `mamba install -c conda-forge sphinx numpydoc`
3) cd docs
4) `sphinx-build -M html source html`
5) Point your browser at the docs generated under html/html
For iterating over errors while changing and fixing things, I replace step 4 with:
`pushd .. ; pip …
> Fix some sphinx issues

- caiman/utils/stats.py
scipy used to wrap numpy.histogram() and several other numpy functions, but stopped with 1.12; stop using the removed wrappers. (not entirely sure I got everything with this)
Fixes #1281
> Fix scipy imports not to use (removed with 1.12) numpy reexports

- caiman/utils/stats.py
When `flag_auto` was set to `True` in dff calculation, there was a significant chance that things could end up in an infinite while loop. 
In the kernel density estimator, an exception which was rarely thrown was exposed recently with some scipy deprecations, so this has started happening a lot lately. It was handled previously with printing 'oops' and returning `None`. This PR fixes that, stops the while loop from recurring indefinitely. The basic logic wasn't terrible it's fine to use `try/except` blocks as control elements in Python, it's just a bad idea to let them go on indefintely. I patched that up, found the explicit exception, and tried to make the logic a little more clear.
#1262 , #1274 , #1283 
caimanmanager test ran fine (demotest is currently running will …
> Handle problem with dff auto-percentile calculation

- README.md
Testing README changes that make caiman central more prominent
> Move and rephrase info on caiman central

- caiman/motion_correction.py
- caiman/source_extraction/cnmf/params.py
- caiman/tests/comparison_humans.py
- caiman/tests/comparison_humans_online.py
- caiman/tests/test_motion_correction.py
- caiman/tests/test_onacid.py
- caiman/utils/utils.py
This is a breaking change that fixes crucial bugs with CNMFParams, and it also adds json loading/saving functions for the same.
1) CNMFParams stores a lot of params with the same names (and even one parameter shares a name with a top level dictionary in the object), causing really weird bugs (including #1153 ). The parser in the codebase (before this diff lands) didn't treat subkeys as being pathed, so whenever a new params dictionary was passed in (including during initialisation) it would be copied to every subkey with its name, not allowing them to be independently set and sometimes causing the code to crash when a bizarre value landed over what was supposed to be a simple scalar. This entirely reworks the change_params() method to instead take a dict with paths inside it that matches …
> WIP: CNMFParams overhaul

- demos/notebooks/demo_pipeline.ipynb
Minor update to `demo_pipeline.ipynb` section on optimizations : added discussion of subsampling before online algorithms.
> Updated discussion of optimizations in cnmf demo

- CONTRIBUTING.md
Minor updates to contributors docs: show how to add upstream branch, and cleaned up some of the jargon/syntax throughout.
> updated contributors doc

- caiman/utils/sbx_utils.py
Fixes build error in #1311 
```caimanmanager test``` passes on 3.11 - if any invalid syntax for <3.11 remains, should be caught in CI
> Fix incompatibilities in test_sbx for python <3.11

- caiman/base/movies.py
- caiman/base/timeseries.py
- caiman/base/traces.py
- caiman/behavior/behavior.py
- caiman/motion_correction.py
- caiman/source_extraction/cnmf/utilities.py
- caiman/tests/comparison_humans.py
- caiman/utils/visualization.py
- demos/general/demo_behavior.py
Will close out item on Roadmap (#1142 ).  
Pylab is a relic of the days when Python was trying to be like Matlab and its use is strongly discouraged [even in its source code](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/pylab.py). This gets rid of it.
It includes things like:
```
from numpy import *
from numpy.fft import *
from numpy.random import *
from numpy.linalg import *
```
And it makes Caiman less readable with `pl.foo()` syntax whereas people expect `plt.foo()` when using the recommended api. 
I'll be testing out things as I go through the different modules. 
One question: should we change the name of the back end in `movies.py` from `pylab` to `matplotlib`? It seems yes.  And, should we warn people? 
My guess is nobody uses it, I have tested it (it works): …
> Remove pylab imports

- caiman/source_extraction/cnmf/spatial.py
- caiman/utils/visualization.py
Handles some minor upcoming deprecations as discussed in issue: Closes #1303 
Tested in demos (dep warnings are gone), and caimanmanager test passes.
> Handle upcoming minor deprecations

- caiman/source_extraction/cnmf/params.py
Issue raised with using reloaded data, the way things are serialized with hdf5, they are loaded as byte-encoded, so when you try to change parameters things don't work (e.g., filename validation throws an error). Rather than digging deeply into serialization in `recursively_load_dict_contents_from_group()` (or the corresponding save function), I added a check for the dtype in `check_consistency()` and if the filenames are not string, do the conversion. This is a bit hacky, but I tested it and it works 😬 
Maybe later we can do more internal validation in the load function, but for now I think this is a good workaround.
Thanks @JohnStout for pointing it out.
Closes #1264 
caimanmanager test works fine. I tested saving/loading and then changing parameters which was broken before, and now it …
> Fix problem with using reloaded cnmf object

- caiman/tests/test_sbx.py
- caiman/utils/sbx_utils.py
This PR includes two changes:
- A bugfix for the condition when a 3D SBX with 3 or 4 planes is converted to TIF. By default, tifffile assumes the 4th dimension is the color channel, so it is necessary to set `photometric` to `MINISBLACK` to avoid each plane being 3-dimensional.
- An added feature, the `plane` argument to SBX loading/conversion functions, which allows extraction of a single plane without keeping the singleton dimension. This is useful when opting to process each plane of a volumetric dataset individually.
Yes, ```caimanmanager test``` passes and new tests have been added for both of these changes.
> SBX utils: ensure correct photometric setting for TIFs and allow extracting single plane

- .github/workflows/run_tests.yml
- environment-minimal.yml
- environment.yml
Be smarter about alternate builds of conda, set channel-priority to handle if user/distro has set it to something else.
This is an attempt to improve on the install issues seen with #1332 
Note that the `channel_priority: true` may seem wrong, but it's a ternary value, with false meaning disabled, true meaning flexible, and strict (a new value) meaning strict. We don't want strict, at least as long as we need tensorflow on Windows. Flexible should do the job.
> environment.yml: handle variant and newer condas better

- caiman/base/movies.py
- docs/source/file_formats.md
This fixes use of scipy APIs that are no longer in scipy to read old-style .mat files. ( #1336 )
Support for the newer hdf5-based mat format is retained (and by newer we're talking about a change made a long time ago).
There were two other ways to fix the import problem:
1) Have a slightly friendlier user message for people trying to load old mat files, by doing try/except in a few places, catching the exception, and guessing that they were trying to load the earlier format and tell them.
2) Attempt to use scipy.io.matlab.loadmat() instead, building support for that back into the codebase (classic mat handling had been broken for awhile and would've needed some work)
I decided not to do the first because it complicates some already complicated code for the sake of an obsolete format (and …
> fix mat support

- caiman/caimanmanager.py
Address #1340 by shifting caimanmanager to use the ignore argument to copytree (and stop using distutils).
> caimanmanager: don't copy __pycache__ dirs out of the library bundle

- caiman/source_extraction/cnmf/spatial.py
Fixes #1348 
Such a minor change that I did not run the full test suite, but confirmed that the issue I was experiencing was fixed as expected. I also did a search for other calls to map_async on an ipyparallel DirectView that could cause an issue, and did not find any (the one exception called `res.get()` right afterwards, which should have the same effect).
> Fix map_async call on DirectView causing error

- caiman/utils/utils.py
I encountered a bug when running a CNMF refit after loading the CNMF object from HDF5. This was caused by `params.spatial['medw']` being `b'NoneType'` rather than `None`.
`None` parameters are currently converted to the string 'NoneType' during saving, which is read back into Python as `b'NoneType'`, and this should be converted back to `None`, but due to the way the conditionals are structured, parameters which should be converted to tuples if not None are not converted if they equal `b'NoneType'`. (They are converted if they are the regular string `'NoneType'`.) I fixed it so that both NoneType cases are handled first, and otherwise simplified the conditional structure (but that should be the only change in behavior).
Partially addresses #1264.
Please delete options that are not …
> Fix medw loading as b'NoneType' instead of None

- caiman/caimanmanager.py
This has caimanmanager try to detect (through some fragile code that's in a try/except) when it's running on an install in editable mode and automatically apply the "inplace" modifier to the install subcommand so the user doesn't need to remember to do that.
This lifts two restrictions on the editable mode install:
1) The need to add --inplace to `caimanmanager install`
2) The need (for inplace only) to be in the source directory (when the opposite is required for a `pip install` without `-e`)
Will merge this as soon as it passes CI as I'm preparing an urgent release to deal with upstream tensorflow breaking us
> caimanmanager detect editable

- caiman/utils/visualization.py
- demos/notebooks/demo_pipeline.ipynb
This PR adds the function `nb_view_quilt()` which is a 1:1 implementation of the `view_quilt()` function in Bokeh. The demo_pipeline notebook referred to an interactive version of the view_quilt function but I was unable to find it. The view_quilt function had a todo for implanting a bokeh version.
When this function is evoked, it shows the quilt plot with 2 sliders for changing the `rf` and `stride` parameters. I opted for modifying the underlaying parameters with the sliders instead of the patch size and overlap, because some width values are impossible to use. For example, the patches can never have a size of 22 because of the formula `patch size = (rf * 2) + 1`.
The demo_pipeline notebook was also modified to use the Bokeh version.
```caimanmanager demotest``` ran without any issues. …
> Added bokeh implementation of view_quilt

- caiman/base/rois.py
- caiman/tests/test_toydata.py
- caiman/utils/visualization.py
The issue is that the `rois.com` function always assumes that each column of `A` is in F-order, but `get_contours` was not taking that into account when calling it with `swap_dim=True`.* In particular, `plot_contours` transposes the image and reverses the order of dimensions input to `get_contours` when `swap_dim` is true. This means that `A` is now in C-order relative to the dimensions.
This solution rewrites `rois.com` to take an `order` parameter. So when `swap_dim` is true, `order` should be 'C'.
Also, with this call fixed, it's unnecessary to call `com` again in `plot_contours` (I believe); the 'CoM' field of each coordinates dict can be used to plot the labels.
\* (I doubt this option is commonly used, but I was using it for 3D CNMF because the way it handles 3D arrays (iterating …
> Get correct centers of mass from rois.com even when swap_dim is True in get_contours

- caiman/mmapping.py
Should address #1373
I'm guessing when I implemented the path relocation function, I didn't refactor it in here correctly, so it was double correcting.
Hoping I don't need to adjust any more code than this and can leave path stuff until the eventual deeper path refactoring I have planned.
(This PR is mostly to run CI)
thanks to @nick-youngblut
> mmapping: fix a path goof where a double-correction caused a problem

- .gitignore
- caiman/base/movies.py
- caiman/summary_images.py
- caiman/tests/test_movies.py
This PR is mainly focused on making sure `local_correlations_movie` works for 3D movies, by adding an `is3D` flag for passing to `caiman.load` and also slightly modifying `movie.removeBL`. I also fixed other occurrences in local_correlations.py where `caiman.load` is used without an `is3D` flag; however, I have not tested whether all these functions actually work for 3D movies.
This fix is necessary to get mesmerize-core's motion correction routine to work for 3D data. But I'd understand if you want to make it a little more broad.
```caimanmanager test``` and ```caimanmanager demotest``` pass. I tested manually by running some of my data through `local_correlations_movie` (both from mesmerize-core and otherwise).
> Fix removeBL for 3D movies

- caiman/utils/utils.py
The function `recursively_save_dict_contents_to_group` checks that an ndarray was written correctly to the HDF5 file by calling `np.array_equal`, but it currently does not set the option `equal_nan=True`, meaning that if there are any NaNs in the array, it returns false. Regardless of whether NaNs are expected, this is probably not what we want if we are just doing a fidelity check.
I initially tried just changing this to true, but apparently it can fail with a TypeError ("ufunc 'isnan' not supported for the input types") in some cases. So I changed it to only be true if the ndarray is of a floating-point type, which seems to work.
Have not tested beyond this; may be good to add a unit test for it, which I can come back and do later.
> Fix error when saving array with NaNs (occurs with corr_img when use_corr_img is True)

- caiman/source_extraction/cnmf/online_cnmf.py
Currently, in the method `OnACID._prepare_object` , `d1` and `d2` are only set when `self.is1p` is true, but are only used if the parameter `online['use_corr_img'] is true. I was trying to run it with `use_corr_img` but without setting the other parameters in a way that causes `is1p` to be true, so I got an unbound local error.
Since these variables are only used in one place in this function, I just moved the line that defines them to be right before they are used. I'm not 100% sure the functionality is correct, but the line just reads from `estimates.dims`, which seems pretty straightforward.
Did not run the tests myself (relying on CI) but I did check that making this change prevented the error I was getting when trying to call `fit_online` …
> Fix unbound local error in online_cnmf when use_corr_img is true but is1p is false

- caiman/tests/test_hdf5.py
- caiman/utils/utils.py
Bugfix for #1385 (using `equal_nan` if `item.dtype.kind == 'f'`)
I added a test for saving to and loading from HDF5 files. `caimanmanager test` passes.
> Compare kind of dtype rather than dtype itself

- caiman/source_extraction/cnmf/map_reduce.py
- caiman/tests/test_toydata.py
Fixes a spot in the code where a sparse matrix was being passed into `np.array`, which is not allowed and throws an error. This block of code seems to execute when low_rank_background is False and nb is not set to 0. 
Partially addresses #1185, nel-lab/mesmerize-core#231.
I made some changes to test_toydata.py so that it can more easily test multiple different sets of parameters, and then I added a couple of sets for batch processing. I confirmed that without this fix, the one called 'patch-not-lowrank' reproduces this error, and with it the tests pass.
> Fix conversion from sparse matrix to dense array when nb == 0 and not low_rank_background

- docs/source/Installation.rst
I added instructions for installing Visual Studio Build Tools 2019 directly from the command line using winget. When I tried installing it from the website https://visualstudio.microsoft.com/vs/older-downloads/, first of all you have to log in with a Microsoft account, and after doing so, at leas for me Build Tools 2019 shows as unavailable. Whereas the winget installation seems to work quickly and seamlessly.
> Add winget instructions for dev mode Windows installation

- Jenkinsfile
- caiman/caimanmanager.py
- caiman/tests/test_memmapping.py
- environment-minimal.yml
- environment.yml
Nose just doesn't work anymore with python 3.12
- All PRs should be made against the **dev** branch. The main branch is not often merged back to dev.
- If you want to get your PR out to the world faster (urgent bugfix), poke pgunn to cut a release; this will get it onto github and into conda faster
```caimanmanager test```
and
```caimanmanager demotest```
include them in the folder 'caiman/tests/` and name them `test_***.py` so they can be included in our lists of tests.
> Try to use pytest for tests

- .github/workflows/run_tests.yml
- README.md
Not happy about this, but right now tensorflow doesn't have windows builds on conda-forge:
https://anaconda.org/conda-forge/tensorflow/files
and we can no longer use the defaults channel for caiman. This means binary conda packages of caiman are not going to happen on Windows until some things change, most likely a pair of things:
A) The upcoming switchover of our code from tensorflow to pytorch (but pytorch also lacks packaging on conda-forge on Windows!)
B) The upstream efforts to get pytorch's packaging issues on conda-forge on Windows fixed: https://github.com/conda-forge/pytorch-cpu-feedstock/pull/231
At that point we can revert these changes and resume packaging conda packages of caiman on Windows, but for now we'll instruct them to install a compiler and use pip. (a recent …
> Windows users: use pip and compile it

- caiman/base/movies.py
Currently, `caiman.bsae.movies.get_file_size` requires reading an entire `.npy` file into memory to infer its shape. This update modifies the function to read only the file header, greatly improving runtime efficiency.
Fixed #1431
- All PRs should be made against the **dev** branch. The main branch is not often merged back to dev.
- If you want to get your PR out to the world faster (urgent bugfix), poke pgunn to cut a release; this will get it onto github and into conda faster
```caimanmanager test```
and
```caimanmanager demotest``` …
> Improve get_file_size efficiency for .npy files

- docs/source/readme-gpu.md
w.r.t. changes in #1433 
btw this is the first time I'm seeing "search for the most recent opencv with openblas and switch to it using existing conda tooling", I have no idea how relevant that is O_O
> remove skcuda stuff from docs

- .github/workflows/run_tests.yml
Apparently the docker images upstream have a new "current" that doesn't have GL packages under the same name. Trying to fix CI by fiddling with package lists.
> Fix CI again

- caiman/base/rois.py
- caiman/motion_correction.py
- caiman/source_extraction/cnmf/params.py
This addresses an issue I raised on the slack where the non-optical flow path of `register_ROIs` seems to have a mistake. It works by finding piecewise-rigid shifts between the two template images using `tile_and_correct`. Then, the matrix of shifts for each patch should be interpolated into a shift map of the same size as the image, to be used for `cv2.remap`. However, these lines:
https://github.com/flatironinstitute/CaImAn/blob/bb55800806f0898592d79dcc705a0b53ccd01ec3/caiman/base/rois.py#L434-L435
actually just [repeat the entries of the matrix, in C-order, to fill in a new matrix of the requested shape](https://numpy.org/doc/1.26/reference/generated/numpy.resize.html), so the result will make no sense.
I used this test script: …
> Fix and add more options for non-optical flow register_ROIs; add feature to interpolate shifts based on patch locations in tile_and_correct

- caiman/mmapping.py
The `caiman.mmapping.load_memmap` function currently supports only `.mmap` files. Since `.npy` files store data in the same format as `.mmap` files, they can be used interchangeably with minor adjustments during loading (due to the header present in `.npy` files).
This update extends `load_memmap` to support `.npy` files, enabling their use in the CNMF parallelization framework.
Fixes #1431 
- All PRs should be made against the **dev** branch. The main branch is not often merged back to dev.
- If you want to get your PR out to the world faster (urgent bugfix), poke pgunn to cut a release; this will get it onto github and into conda faster …
> Add npy support to load_memmap

- caiman/base/movies.py
- caiman/source_extraction/cnmf/cnmf.py
- caiman/source_extraction/cnmf/initialization.py
- caiman/source_extraction/cnmf/temporal.py
NumPy 2.0 removed the `np.Inf` constant. To ensure compatibility with newer versions of NumPy, all instances of `np.Inf` have been replaced with `np.inf`. This change is fully backward-compatible, as `np.inf` has always been defined in NumPy.
Verified that `np.inf` works across multiple NumPy versions.
> Numpy 2.0 compatibility: change all np.Inf to np.inf

- caiman/source_extraction/volpy/volpy_gui.py
- environment.yml
- pyproject.toml
Upstream changes in pyqtgraph late last year broke the volpy gui because mixing pyqtgraph and PyQt5 became impossible (pyqtgraph routed itself through pyside6 if it's present, causing the app to mix PyQt5 and QT6 objects).
This diff commits volpy to using QT6 through the pyside6 library, avoiding possibilities of mixing them.
> Addresses #1454 using pyside6

- caiman/source_extraction/cnmf/initialization.py
- caiman/source_extraction/cnmf/params.py
This adds a mechanism to greedyROI() to allow overriding of calls to sklearn's NMF(), passing in overrides as a dict.
(it also, as usual, includes some minor cleanups I spotted while looking at the code).
Will be WIP until the mechanism is plumbed up to CNMFParams, which will go through initialization.py:initialize_components() as well as utilities.py:manually_refine_components() although we may decide not to do it for the latter one maybe.
I went back-and-forth over whether to go with a dict or pass in params individually, but I think grouping them at least at this level is a little closer to where we eventually want to be - passing a structured deep dictionary parameters object around rather than having dozens of arguments everywhere and unwieldy gigantic signatures to all …
> CNMF.initialization.greedyROI() - Add a limited mechanism to specify params in calls to sklearn's NMF

- caiman/source_extraction/cnmf/online_cnmf.py
- caiman/source_extraction/cnmf/params.py
This has the OnACID (online) constructor catch when the number of splits appropriate for mainline processing are bad for initialisation, telling the user they need to adjust provided parameters.
It's not necessarily the best way to handle this; I thought about:
A) having it automatically increase the batch size for initialisation, 
B) Having it ignore splits_rig for initialisation
On the first, it seems this would be a major change in behaviour of the code, possibly disrupting existing workflows (finding more components, increasing memory requirements, ???)
On the second, this would be a lot of work and may also change behaviour of the code in ways I can't anticipate
For now, raising an exception and letting the user handle it by providing different parameters seems less disruptive, and …
> Handle cases where parameters end up with bad values for OnACID given long movies
